apiVersion: v2
name: sd-securities-settlement
description: "BIAN Service Domain: Securities Settlement (Process pattern, Operations and Execution)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - process
annotations:
  bian/business-area: "Operations and Execution"
  bian/business-domain: "Securities"
  bian/asset-type: "Securities Settlement"
  bian/control-record: "Securities Settlement Procedure"
